runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /models
  static_dir: models
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'
